const config = require("../config");

const verificationMailTemplate = async (data, token) => {
  return `<table class="es-content" cellspacing="0" cellpadding="0" align="center" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important"><tbody><tr class="es-visible-simple-html-only"><td class="es-stripe-html" align="center" style="padding:0;Margin:0"><table class="es-content-body" cellspacing="0" cellpadding="0" bgcolor="#ffffff" align="center" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#FFFFFF;width:600px"><tbody><tr><td align="left" style="padding:40px;Margin:0"><table cellspacing="0" cellpadding="0" width="100%" role="none" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tbody><tr><td align="left" style="padding:0;Margin:0;width:520px"><table cellspacing="0" cellpadding="0" width="100%" role="presentation" style="mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px"><tbody><tr><td align="center" style="padding:0;Margin:0;font-size:0"><img src="https://feoxawv.stripocdn.email/content/guids/CABINET_817af30c32eb4cbfe0b9cf3ab48d5c77b64ad4e1623d099dbe8854c394fcc87b/images/logo.png" alt="" width="335" style="display:block;font-size:14px;border:0;outline:none;text-decoration:none"></td>
  </tr><tr><td align="left" style="padding:0;Margin:0;padding-top:60px;padding-right:25px;padding-bottom:10px"><h1 style="Margin:0;font-family:arial, 'helvetica neue', helvetica, sans-serif;mso-line-height-rule:exactly;letter-spacing:0;font-size:30px;font-style:normal;font-weight:normal;line-height:36px;color:#333333">Hii, ${data.username}</h1></td></tr><tr><td align="left" style="padding:0;Margin:0;padding-right:25px;padding-bottom:10px;padding-top:10px"><h3 style="Margin:0;font-family:arial, 'helvetica neue', helvetica, sans-serif;mso-line-height-rule:exactly;letter-spacing:0;font-size:20px;font-style:normal;font-weight:normal;line-height:24px;color:#333333" align="left">Click here to verify your email address and start using our application.</h3></td></tr>
  <tr><td align="center" style="padding:0;Margin:0;padding-top:5px;padding-right:10px"><span class="es-button-border" style="border-style:solid;border-color:#2CB543;background:#00aae5;border-width:0px 0px 2px 0px;display:inline-block;border-radius:42px;width:auto;border-left-color:#2cb543"><a href="${config.baseURL}verify-account?token=${token}" class="es-button" target="_blank" style="mso-style-priority:100 !important;text-decoration:none !important;mso-line-height-rule:exactly;color:#FFFFFF;font-size:18px;padding:10px 20px 10px 20px;display:inline-block;background:#00aae5;border-radius:42px;font-family:arial, 'helvetica neue', helvetica, sans-serif;font-weight:normal;font-style:normal;line-height:22px;width:auto;text-align:center;letter-spacing:0;mso-padding-alt:0;mso-border-alt:10px solid #00aae5">Verify</a></span></td></tr>
  <tr><td align="left" style="padding:0;Margin:0;padding-right:25px;padding-bottom:10px;padding-top:40px"><h6 style="Margin:0;font-family:arial, 'helvetica neue', helvetica, sans-serif;mso-line-height-rule:exactly;letter-spacing:0;font-size:16px;font-style:normal;font-weight:normal;line-height:19px;color:#333333" align="center"><strong>[Note: This link will expire in 24 Hours.]</strong></h6></td></tr><tr><td align="left" style="padding:0;Margin:0;padding-right:25px;padding-bottom:10px;padding-top:30px"><h5 style="Margin:0;font-family:arial, 'helvetica neue', helvetica, sans-serif;mso-line-height-rule:exactly;letter-spacing:0;font-size:20px;font-style:normal;font-weight:normal;line-height:24px;color:#333333">Best regards,<br></h5>
 <h5 style="Margin:0;font-family:arial, 'helvetica neue', helvetica, sans-serif;mso-line-height-rule:exactly;letter-spacing:0;font-size:20px;font-style:normal;font-weight:normal;line-height:24px;color:#333333">The <a href="https://webosmotic.com/" target="_blank" style="mso-line-height-rule:exactly;text-decoration:underline;color:#1376C8;font-size:20px">Webosmotic</a> Team</h5></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table>`;
};

module.exports = {
  verificationMailTemplate,
};
